name: My First Workflow

on:
  push:
    branches: #[ main ]
      - main
  # pull_request:
  #   branches: [ main ]

jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo code
        uses: actions/checkout@v2

      - name: Say Hello
        run: |
          echo "Hello, World!"
          echo "This is my first GitHub Actions workflow."
          pwd
          chmod +x ./scripts/hello.sh
          ./scripts/hello.sh 
          echo "My first Secret data: ${{ secrets.MY_SECRET }}"
          echo "My first Environment variable: ${{ vars.MY_VARIABLE }}"
  
  second-run:
    runs-on: ubuntu-latest
    needs: first-run # it allows to run this job after the successful completion of the first-run job
    #if: failure() # it allows to run this job only if the first-run job fails 
    #if: success() # it allows to run this job only if the first-run job succeeds, even if the first-run job fails, this job will not run. Also we skip adding success by default it is success().
    steps:
      - name: Checkout Repo code
        uses: actions/checkout@v6

      - name: Say Hello Again
        run: |
          echo "Hello again, World!"
          echo "This is my second job in the workflow."
          pwd
          # chmod +x ./scripts/hello.sh
          # ./scripts/hello.sh 
          # echo "My first Secret data: ${{ secrets.MY_SECRET }}"
          # echo "My first Environment variable: ${{ vars.MY_VARIABLE }}"

  third-run:
    runs-on: ubuntu-latest
    needs: [first-run, second-run] # it allows to run this job after the successful completion of the first-run and second-run jobs
    if: failure() 
    
    steps:
      - name: Checkout Repo code
        uses: actions/checkout@v6

      - name: Say Hello Again and Again
        run: |
          echo "Hello again and again, World!"
          echo "This is my third job in the workflow."
          pwd

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Run tests
  #       run: |
  #         pytest tests/
  # build: